# Generated by Django 3.1.7 on 2021-02-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210214_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
